library(fields)

setwd("~/Desktop/Genomics_work")

pdf("assembly_summary_stats.pdf", height=8, width=10.5)

soap_assembly_stats <- read.table("soap_summary_stats.txt", header = TRUE, sep = "\t")
soap_cap3_assembly_stats <- read.table("soap_CAP3_summary_stats.txt", header = TRUE, sep = "\t")
velvet_assembly_stats <- read.table("velvet_summary_stats.txt", header = TRUE, sep = "\t")
velvet_cap3_assembly_stats <- read.table("velvet_CAP3_summary_stats.txt", header = TRUE, sep = "\t")
sga_processed_assembly_stats <- read.table("fungal_assembly_processed_data_scaffolds_assembly_stats.txt")
sga_raw_assembly_stats <- read.table("fungal_assembly_raw_data_scaffolds_assembly_stats.txt")
sga_cap3_processed_assembly_stats <- read.table("sga_CAP3_singles_contigs_assembly_stats.txt")
sga_cap3_raw_assembly_stats <- read.table("sga_raw_CAP3_singles_contigs_assembly_stats.txt")
cap3_merged_assembly_stats <- read.table("merged_assembly_cap3_singles_contigs_assembly_stats.txt")
cap3_merged_reassembly_stats <- read.table("merged_reassembly_CAP3_singles_contigs_assembly_stats.txt")
par(mfrow=c(2,2))

plot(-100, -100, xlim=c(min(soap_assembly_stats$K), max(soap_assembly_stats$K)), ylim=c(min(min(soap_assembly_stats$raw_scaffold_num), min(soap_assembly_stats$processed_scaffold_num), min(soap_cap3_assembly_stats$raw_scaffold_num), min(soap_cap3_assembly_stats$processed_scaffold_num)), max(max(soap_assembly_stats$raw_scaffold_num), max(soap_assembly_stats$processed_scaffold_num), max(soap_cap3_assembly_stats$raw_scaffold_num), max(soap_cap3_assembly_stats$processed_scaffold_num))), xlab='kmer', ylab='number of scaffolds', main='Total Scaffolds', frame.plot=T)
grid(NA, NULL, col = 'lightgrey', lty = 1)
abline(v = soap_assembly_stats$K, col = 'lightgrey')
lines(soap_assembly_stats$K, soap_assembly_stats$raw_scaffold_num, col='red', lwd=2)
lines(soap_assembly_stats$K, soap_assembly_stats$processed_scaffold_num, col='black', lwd=2)
lines(soap_cap3_assembly_stats$K, soap_cap3_assembly_stats$raw_scaffold_num, col='red', lwd=2, lty=2)
lines(soap_cap3_assembly_stats$K, soap_cap3_assembly_stats$processed_scaffold_num, col='black', lwd=2, lty=2)
lines(velvet_assembly_stats$K, velvet_assembly_stats$scaffold_num, col='blue', lwd=2)
lines(velvet_cap3_assembly_stats$K, velvet_cap3_assembly_stats$scaffold_num, col='blue', lwd=2, lty=2)
points(c(69,69,69,69,69,69), c(sga_processed_assembly_stats$V2[1], sga_raw_assembly_stats$V2[1], sga_cap3_processed_assembly_stats$V2[1], sga_cap3_raw_assembly_stats$V2[1], cap3_merged_assembly_stats$V2[1], cap3_merged_reassembly_stats$V2[1]), pch = c(17,17,2,2,18,5), col = c('green', 'blue', 'green', 'blue', 'purple', 'purple'), cex = 1.5)
legend(69, max(soap_assembly_stats$raw_scaffold_num), c("SOAP Raw Data", "SOAP Processed Data", "Velvet", "SOAP/Velvet Merged", "SGA Processed Data", "SGA Raw Data", "Initial Assembly", "CAP3 Reassembly"), lty = c(1,1,1,NA,NA,NA,1,2), pch = c(NA, NA, NA, 18, 17, 17, 15, 0), col = c("red", "black", "blue", "purple", "green", "blue", "black", "black"), cex=0.9)

plot(-100, -100, xlim=c(min(soap_assembly_stats$K), max(soap_assembly_stats$K)), ylim=c(min(min(soap_assembly_stats$raw_max_len), min(soap_assembly_stats$processed_max_len), min(soap_cap3_assembly_stats$raw_max_len), min(soap_cap3_assembly_stats$processed_max_len)), max(max(soap_assembly_stats$raw_max_len), max(soap_assembly_stats$processed_max_len), max(soap_cap3_assembly_stats$raw_max_len), max(soap_cap3_assembly_stats$processed_max_len))), xlab='kmer', ylab='maximum length', main='Maximum Scaffold Length', frame.plot=T)
grid(NA, NULL, col = 'lightgrey', lty = 1)
abline(v = soap_assembly_stats$K, col = 'lightgrey')
lines(soap_assembly_stats$K, soap_assembly_stats$raw_max_len, col='red', lwd=2)
lines(soap_assembly_stats$K, soap_assembly_stats$processed_max_len, col='black', lwd=2)
lines(soap_cap3_assembly_stats$K, soap_cap3_assembly_stats$raw_max_len, col='red', lwd=2, lty=2)
lines(soap_cap3_assembly_stats$K, soap_cap3_assembly_stats$processed_max_len, col='black', lwd=2, lty=2)
lines(velvet_assembly_stats$K, velvet_assembly_stats$max_len, col='blue', lwd=2)
lines(velvet_cap3_assembly_stats$K, velvet_cap3_assembly_stats$max_len, col='blue', lwd=2, lty=2)
points(c(69,69,69,69,69,69), c(sga_processed_assembly_stats$V2[5], sga_raw_assembly_stats$V2[5], sga_cap3_processed_assembly_stats$V2[5], sga_cap3_raw_assembly_stats$V2[5], cap3_merged_assembly_stats$V2[5], cap3_merged_reassembly_stats$V2[5]), pch = c(17,17,2,2,18,5), col = c('green', 'blue', 'green', 'blue', 'purple', 'purple'), cex = 1.5)

plot(-100, -100, xlim=c(min(soap_assembly_stats$K), max(soap_assembly_stats$K)), ylim=c(min(min(soap_assembly_stats$raw_N50), min(soap_assembly_stats$processed_N50), min(soap_cap3_assembly_stats$raw_N50), min(soap_cap3_assembly_stats$processed_N50)), max(max(soap_assembly_stats$raw_N50), max(soap_assembly_stats$processed_N50), max(soap_cap3_assembly_stats$raw_N50), max(soap_cap3_assembly_stats$processed_N50))), xlab='kmer', ylab='N50', main='N50', frame.plot=T)
grid(NA, NULL, col = 'lightgrey', lty = 1)
abline(v = soap_assembly_stats$K, col = 'lightgrey')
lines(soap_assembly_stats$K, soap_assembly_stats$raw_N50, col='red', lwd=2)
lines(soap_assembly_stats$K, soap_assembly_stats$processed_N50, col='black', lwd=2)
lines(soap_cap3_assembly_stats$K, soap_cap3_assembly_stats$raw_N50, col='red', lwd=2, lty=2)
lines(soap_cap3_assembly_stats$K, soap_cap3_assembly_stats$processed_N50, col='black', lwd=2, lty=2)
lines(velvet_assembly_stats$K, velvet_assembly_stats$N50, col='blue', lwd=2)
lines(velvet_cap3_assembly_stats$K, velvet_cap3_assembly_stats$N50, col='blue', lwd=2, lty=2)
points(c(69,69,69,69,69,69), c(sga_processed_assembly_stats$V2[2], sga_raw_assembly_stats$V2[2], sga_cap3_processed_assembly_stats$V2[2], sga_cap3_raw_assembly_stats$V2[2], cap3_merged_assembly_stats$V2[2], cap3_merged_reassembly_stats$V2[2]), pch = c(17,17,2,2,18,5), col = c('green', 'blue', 'green', 'blue', 'purple', 'purple'), cex = 1.5)

plot(-100, -100, xlim=c(min(soap_assembly_stats$K), max(soap_assembly_stats$K)), ylim=c(min(min(soap_assembly_stats$raw_assembled_bases), min(soap_assembly_stats$processed_assembled_bases), min(soap_cap3_assembly_stats$raw_assembled_bases), min(soap_cap3_assembly_stats$processed_assembled_bases)), max(max(soap_assembly_stats$raw_assembled_bases), max(soap_assembly_stats$processed_assembled_bases), max(soap_cap3_assembly_stats$raw_assembled_bases), max(soap_cap3_assembly_stats$processed_assembled_bases))), xlab='kmer', ylab='assembled bases', main='Assembly Size', frame.plot=T)
grid(NA, NULL, col = 'lightgrey', lty = 1)
abline(v = soap_assembly_stats$K, col = 'lightgrey')
lines(soap_assembly_stats$K, soap_assembly_stats$raw_assembled_bases, col='red', lwd=2)
lines(soap_assembly_stats$K, soap_assembly_stats$processed_assembled_bases, col='black', lwd=2)
lines(soap_cap3_assembly_stats$K, soap_cap3_assembly_stats$raw_assembled_bases, col='red', lwd=2, lty=2)
lines(soap_cap3_assembly_stats$K, soap_cap3_assembly_stats$processed_assembled_bases, col='black', lwd=2, lty=2)
lines(velvet_assembly_stats$K, velvet_assembly_stats$assembled_bases, col='blue', lwd=2)
lines(velvet_cap3_assembly_stats$K, velvet_cap3_assembly_stats$assembled_bases, col='blue', lwd=2, lty=2)
points(c(69,69,69,69,69,69), c(sga_processed_assembly_stats$V2[4], sga_raw_assembly_stats$V2[4], sga_cap3_processed_assembly_stats$V2[4], sga_cap3_raw_assembly_stats$V2[4], cap3_merged_assembly_stats$V2[4], cap3_merged_reassembly_stats$V2[4]), pch = c(17,17,2,2,18,5), col = c('green', 'blue', 'green', 'blue', 'purple', 'purple'), cex = 1.5)

par(mfrow=c(1,1))
dev.off()
